<?php

return [
    "Hey there sexy!",
    "I hope your day is as nice as your face!",
    "Have you been working out?",
    "If I could high five you... I would!",
    "On a scale from 1 to 10, you're an 15!",
    "Being awesome is hard, but you'll manage",
    "I see a lot of myself in you",
    "Damn. You're looking good!",
    "Yes, you are the fairest of them all",
    "There's no place like home",
    "If you focus on what you’ve left behind, you will never be able to see what lies ahead",
    "Strangers all wanna sit next to you on the bus",
    "Coworkers fantasizes about getting stuck in the elevator with you",
    "At least two friends are going to name their child and/or goldfish after you",
    "The FBI tapped your phone just to hear the sound of your voice",
    "Kids think you are the “cool old person”",
    "Your smile is contagious",
    "You look great today",
    "You're a smart cookie",
    "I like your style",
    "You have the best laugh",
    "I appreciate you",
    "You are the most perfect you there is",
    "Your perspective is refreshing",
    "You're an awesome friend",
    "You light up the room",
    "You deserve a hug right now",
    "You should be proud of yourself",
    "You're more helpful than you realize",
    "You have a great sense of humor",
    "You've got all the right moves!",
    "You're all that and a super-size bag of chips",
    "You're even more beautiful on the inside than you are on the outside",
    "If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now",
    "You are making a difference",
    "You're like sunshine on a rainy day",
    "You bring out the best in other people",
    "You're a great listener",
    "How is it that you always look great, even in sweatpants?",
    "Everything would be better if more people were like you!",
    "I bet you sweat glitter",
    "You were cool way before hipsters were cool",
    "You smell really good",
    "Being around you makes everything better!",
    "When you say, \"I meant to do that,\" I totally believe you",
    "Colors seem brighter when you're around",
    "You're wonderful",
    "You're better than a triple-scoop ice cream cone. With sprinkles",
    "Your hair looks stunning",
    "You're one of a kind!",
    "You're inspiring",
    "You should be thanked more often. So thank you!!",
    "You have the best ideas",
    "You always know how to find that silver lining",
    "Everyone gets knocked down sometimes, but you always get back up and keep going",
    "You're a candle in the darkness",
    "You're a great example to others",
    "Being around you is like being on a happy little vacation",
    "You always know just what to say",
    "You're always learning new things and trying to better yourself, which is awesome",
    "You're more fun than bubble wrap",
    "When you make a mistake, you fix it",
    "You're great at figuring stuff out",
    "The people you love are lucky to have you in their lives",
    "You're like a breath of fresh air",
    "You're gorgeous -- and that's the least interesting thing about you, too",
    "You're so thoughtful",
    "Your creative potential seems limitless",
    "You're irresistible when you blush",
    "Actions speak louder than words, and yours tell an incredible story",
    "Somehow you make time stop and fly at the same time",
    "When you make up your mind about something, nothing stands in your way",
    "You seem to really know who you are",
    "Any team would be lucky to have you on it",
    "You're even better than a unicorn, because you're real",
    "How do you keep being so funny and making everyone laugh?",
    "You have a good head on your shoulders",
    "You're really something special",
    "You're a gift to those around you",
    "You're so smart! Why haven't I thought of that before?",
    "You look great in that outfit",
    "I like the way you smile",
    "You're so funny!",
    "Thank you for being so thoughtful",
    "I like your sense of style",
    "Your hair looks amazing",
    "You smell good today",
    "You rock that shirt!",
    "I like the way you designed my website",
    "I love all of the photos you've taken",
    "Have been working out lately?",
    "Take a break! You deserve a vacation",
    "How do make your skin to look flawless and radiant?",
    "You are one of a kind",
    "Keep up the good work!",
    "You nailed it!",
    "9/10 dentists agree, you are the BEST",
    "Your hair looks great today. It also looked really good two days ago",
    "You deserve a promotion",
    "That looks nice on you",
    "Your smile is breath taking",
    "You make my data circuits skip a beat",
    "You're cooler than Pirates and Ninjas combined",
    "You could probably lead a rebellion",
    "Your skin is radiant",
    "You're so rad",
    "You're more fun than a barrel of monkeys",
    "You're nicer than a day on the beach",
    "Your glass is the fullest",
    "You look so perfect",
    "You're more fun than bubble wrap",
    "You're the bee's knees",
    "You definitely know the difference between your and you're",
    "You got the moves like Jagger",
    "I would volunteer to take your place in the Hunger Games",
    "You have such nice eyes",
    "You're awesome",
    "You're the best",
    "You're fantastic",
    "You're really flipping smart",
    "You look awesome today, seriously",
];